name: test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Test module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Pester -MinimumVersion 6.0.1 -Force -Scope CurrentUser
          Install-Module ImportExcel -MinimumVersion 7.8.10 -Force -Scope CurrentUser
          Invoke-Pester -Path ./tests -CI
